# Generated by Django 4.1.4 on 2022-12-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rightgroups_rights_userrights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rights',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
